name: Continuous Integration

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: 'continuous-integration'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Tests
        run: pnpm run test
